framework:
    templating:
        engines: ['twig']
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.project_dir%/var/sessions/%sulu.context%/%kernel.environment%"
    csrf_protection: ~

dubture_f_fmpeg:
    ffmpeg_binary: /usr/local/bin/ffmpeg # path to ffmpeg
    ffprobe_binary: /usr/local/bin/ffprobe # path to ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 4

sulu_document_manager:
    sessions:
        default:
            backend:
                type: doctrinedbal
            workspace: "default"
            username: "admin"
            password: "admin"
        live:
            backend:
                type: doctrinedbal
            workspace: "default_live"
            username: "admin"
            password: "admin"

sulu_core:
    webspace:
        config_dir: "%kernel.project_dir%/config/sulu/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
            paths:
                homepage:
                    path: "%kernel.project_dir%/config/sulu/templates/pages"
                    type: "home"
                page:
                    path: "%kernel.project_dir%/config/sulu/templates/pages"
                    type: "page"
                snippet:
                    path: "%kernel.project_dir%/config/sulu/templates/snippets"
                    type: "snippet"
