# By default, the bundle will be active on all connections registered,
# but you can specify explicitly which connections it should be enabled on.
# Defaults to empty array []

#biig_domain:
#    entity_managers: ['default']
