eu_login_api_authentication:
    client_id: "%env(EULOGIN_CLIENT_ID)%"
    client_secret: "%env(EULOGIN_CLIENT_SECRET)%"
    environment: "%env(EULOGIN_ENV)%" # Available values are: acceptance, production
