#  See https://github.com/nbgrp/env-bundle#readme for detailed configuration
nbgroup_env:
    array_cast: false  #  "true" to enable Array Cast processor
    csv: false         #  set delimiters mapping to enable CSV processor (see below)

#    csv:              #  enable CSV processor
#        dot: '.'      #  "csv-dot:FOO" will parse env FOO into array with "." as a separator
#        colon: ':'    #  "csv-colon:FOO" will parse env FOO into array with ":" as a separator
