fpt_stripe:
    credentials:
        publishable_key: "%env(STRIPE_PUBLISHABLE_KEY)%"
        secret_key: "%env(STRIPE_SECRET_KEY)%"
        webhook_signature_key: "%env(STRIPE_WEBHOOK_SIGNATURE_KEY)%"