meili_search:
    url: '%env(MEILISEARCH_URL)%'
    api_key: '%env(MEILISEARCH_API_KEY)%'
    prefix: '%env(MEILISEARCH_PREFIX)%' # Use a prefix for index names based on env var
#    indices:
#        - name: samples
#          class: App\Entity\Sample
#        - name: other_samples
#          class: App\Entity\OtherSample
