fitbit:
    clientId: '%env(FITBIT_CLIENT_ID)%'
    clientSecret: '%env(FITBIT_CLIENT_SECRET)%'
    scopes:
        - activity
        - heartrate
        - location
        - nutrition
        - profile
        - settings
        - sleep
        - social
        - weight
