services:
    loophp\RepositoryMonadicHelper\MonadicRepositoryFactory:
        autowire: true
        autoconfigure: true

    loophp\RepositoryMonadicHelper\MonadicRepositoryFactoryInterface: '@loophp\RepositoryMonadicHelper\MonadicRepositoryFactory'
