datatable:
    # Load i18n data from DataTables CDN or locally
    language_from_cdn: false
    # Language of the Datatables (if language_from_cdn true)
    language: 'English'
    # Default options to load into DataTables
    # options:
    #    stateSave: true
    # Default parameters to be passed to the template
    template_parameters:
        # Default Datatables style (one from none,bootstrap3,bootstrap4,bootstrap5,foundation,bulma,jqueryui)
        style: 'bootstrap5'
        # Default class attribute to apply to the root table elements (change it to be compatible with the style)
        className: 'table table-bordered'
