sonata_admin:
    providers:
        - sonata.media.provider.image
        - sonata.media.provider.video

    assets:
        extra_stylesheets:
            - bundles/sonatamultiupload/dist/sonata-multiupload.css

        extra_javascripts:
            - bundles/sonatamultiupload/dist/sonata-multiupload.js
