services:
    _defaults:
        autowire: true

    Datana\FakeApi\Api\FakeApiClient:
        arguments:
            - '%env(FAKE_API_BASE_URI)%'
            - '%env(FAKE_API_USERNAME)%'
            - '%env(FAKE_API_PASSWORD)%'
            - '%env(bool:FAKE_API_DISABLE_CACHE)%'

    Datana\FakeApi\Api\Formulario\DateneingabenApi: null
    Datana\FakeApi\Api\Formulario\StatisticsApi: null
