parameters:
    # Add a fallback SENTRY_DSN if the env var is not set. This allows you to
    # run cache:warmup even if your environment variables are not available yet.
    # You should not need to change this value.
    env(SENTRY_DSN): ''

sentry:
    dsn: '%env(resolve:SENTRY_DSN)%'

    options:
        curl_method: async

#    skip_capture:  # To skip certain exceptions, specify a list below
#      - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
#      - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
#      - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
