security:
    providers:
        ctp:
            id: Commercetools\Symfony\CustomerBundle\Security\User\UserProvider
    access_control:
        - { path: /user/, roles: ROLE_USER }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Commercetools\Symfony\CustomerBundle\Security\User\User: plaintext
    firewalls:
        main:
            anonymous: ~
            commercetools-login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
