biig_domain:
    # Learn more about configuration in the bundle configuration reference
    # https://github.com/biig-io/DomainComponent/blob/v1/docs/domain_event_dispatcher.md#configuration-reference

    # Post persist events are *not* activated by default, you need to enable the post persist listeners
    persist_listeners:
        # As doctrine supports many connections, you need to enable your connections one by one
        doctrine: ['default']

