ambta_doctrine_encrypt:
    # Encryption algorithm; You can choose between Halite and Defuse
    # You need to install the needed package for the algo you choose to use
    encryptor_class: Halite # Or Defuse
