services:
    Datana\Bridge\Symfony\Mailer\Sendgrid\Transport\SendgridDynamicTemplateTransportFactory:
        parent: 'mailer.transport_factory.abstract'
        tags: ['mailer.transport_factory']
        autowire: true
