jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
#        auto_detection: false
        directories:
            app:
                namespace_prefix: "App"
                path: "%kernel.project_dir%/metadata/jms_serializer"
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
