services:
    _defaults:
        autowire: true

    Datana\Datapool\Api\DatapoolClient:
        arguments:
            - '%env(DATAPOOL_API_BASE_URI)%'
            - '%env(DATAPOOL_API_USERNAME)%'
            - '%env(DATAPOOL_API_PASSWORD)%'
