sulu_article:
    index_name: '%env(resolve:ELASTICSEARCH_INDEX)%'
    hosts:
        - '%env(resolve:ELASTICSEARCH_HOST)%'
    types:
        article:
            translation_key: "sulu_article.article"

sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: schema
            options:
                route_schema: '/articles/{object.getTitle()}'
        Sulu\Bundle\ArticleBundle\Document\ArticlePageDocument:
            generator: article_page
            options:
                route_schema: '{translator.trans("page")}-{object.getPageNumber()}'
                parent: '{object.getParent().getRoutePath()}'

ongr_elasticsearch:
# If you expect more than 10000 articles, you need to set the `max_result_window` to an appropriate number
#    managers:
#        default:
#            index:
#                settings:
#                    max_result_window: 20000
#        live:
#            index:
#                settings:
#                    max_result_window: 20000

    analysis:
        tokenizer:
            pathTokenizer:
                type: path_hierarchy
        analyzer:
            pathAnalyzer:
                tokenizer: pathTokenizer
