fluffy_discord_road_runner:
    # Optional
    # Specify relative path from "kernel.project_dir" to your RoadRunner config file
    # if you want to run cache:warmup without having your RoadRunner running in background,
    # e.g. when building Docker images. Default is ".rr.yaml"
    rr_config_path: ".rr.yaml"

    # https://docs.roadrunner.dev/http/http
    http:
        # Optional
        # -----------
        # This decides when to boot the Symfony kernel.
        #
        # false (default) - before first request (worker takes some time to be ready, but app has consistent response times)
        # true - once first request arrives (worker is ready immediately, but inconsistent response times due to kernel boot time spikes)
        #
        # If you use large amount of workers, you might want to set this to true or else the RR boot up might
        # take a lot of time or just boot up using only a few "emergency" workers
        # and then use dynamic worker scaling as described here https://docs.roadrunner.dev/php-worker/scaling
        lazy_boot: false

        # Optional
        # -----------
        # This decides if Symfony routing should be preloaded when worker starts and boots Symfony kernel.
        # This option halves the initial request response time.
        # (based on a project with over 400 routes and quite a lot of services, YMMW)
        #
        # true (default in PROD) - sends one dummy (empty) HTTP request to the kernel to initialize routing and services around it
        # false (default in DEV) - only when first worker request arrives, routing and services are loaded
        #
        # You might want to create a dummy "/" route for the route to "land",
        # or listen to onKernelRequest events and look in the request for the attribute
        # FluffyDiscord\RoadRunnerBundle\Worker\HttpWorker::DUMMY_REQUEST_ATTRIBUTE
        # Set this to "false" if you have any issues and report them to me.
        early_router_initialization: true

    # https://docs.roadrunner.dev/plugins/centrifuge
    centrifugo:
        # Optional
        # -----------
        # See http section
        lazy_boot: false

    # https://docs.roadrunner.dev/key-value/overview-kv
    kv:
        # Optional
        # -----------
        # If true (default), bundle will automatically register all "kv" adapters in your .rr.yaml.
        # Registered services have alias "cache.adapter.rr_kv.NAME"
        auto_register: true

        # Optional
        # -----------
        # Which serializer should be used.
        # By default, "IgbinarySerializer" will be used if "igbinary" php extension
        # is installed (recommended), otherwise "DefaultSerializer".
        # You are free to create your own serializer, it needs to implement
        # Spiral\RoadRunner\KeyValue\Serializer\SerializerInterface
        serializer: null

        # Optional
        # -----------
        # Specify relative path from "kernel.project_dir" to a keypair file
        # for end-to-end encryption. "sodium" php extension is required.
        # https://docs.roadrunner.dev/key-value/overview-kv#end-to-end-value-encryption
        keypair_path: bin/keypair.key

when@dev:
    fluffy_discord_road_runner:
        http:
            early_router_initialization: false
