# |--------------------------------------------------------------------------
# | CSRF Protection
# |--------------------------------------------------------------------------

# uncomment if you use PHP attributes
# controllers:
#     resource:
#         path: ../../src/Controller/
#         namespace: App\Controller
#     type: attribute
#     defaults:
#         csrf:
#             create: true
#             require: ['POST', 'PUT', 'PATCH', 'DELETE']

# uncomment if you use annotations
# controllers:
#     resource: ../../src/Controller/
#     type: annotation
#     defaults:
#         csrf:
#             create: true
#             require: ['POST', 'PUT', 'PATCH', 'DELETE']
