services:
    _defaults:
        autowire: true

    Inpsyde\LogzIoMonolog\Handler\LogzIoHandler:
        arguments:
            $token: '%env(LOGZ_IO_TOKEN)%'
            $host: 'listener-eu.logz.io'

    Datana\LogzIo\Handler\Logger\Processor\AddApplicationNameProcessor:
        arguments:
            - '%env(LOGZ_IO_APPLICATION_NAME)%'
        tags: ['monolog.processor']
