# Read documentation at https://github.com/async-aws/symfony-bundle
async_aws:
        region: eu-central-1
        accessKeyId: '%env(AWS_KEY)%'
        accessKeySecret: '%env(AWS_SECRET)%'

    # All installed clients are automatically autowired. Use this section to customize clients
    clients:

    # Use AWS SSM to store secrets or parameters.
    #secrets:
        #path: /parameters/my-project
