goetas_twital:
    full_twig_compatibility: true # see http://twitalbundle.readthedocs.io/en/latest/#full-twig-compatibility

## add here your custom extension handlers, by default Twital parses *.html.twital, *.xml.twital and *.xhtml.twital files
## more info about it on http://twitalbundle.readthedocs.io/en/latest/#source-adapters
#    source_adapter:
#        - { service: twital.source_adapter.html5, pattern: ['/\.ext\.twital$/', '/\.ext2\.twital$/'] }
