# See Readme at https://github.com/arad021/entity-already-exists-validation-constraint
services:
    Arad021\Validator\Constraint\EntityNotExistValidator:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [ 'validator.constraint_validator' ]
