notify_notyf:
    scripts:
        - 'https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js'
    styles:
        - 'https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css'
    options:
        duration: 5000
        ripple: false
        position:
            x: 'right'
            y: 'top'
        dismissible: false
        types:
            -   type: 'success'
                className: 'notyf__toast--success'
                backgroundColor: '#3dc763'
                icon:
                    className: 'notyf__icon--success'
                    tagName: 'i'
            -   type: 'error'
                className: 'notyf__toast--error'
                backgroundColor: '#ed3d3d'
                icon:
                    className: 'notyf__icon--error'
                    tagName: 'i'
            -   type: 'info'
                className: 'notyf__toast--info'
                backgroundColor: '#5784E5'
                icon: false
            -   type: 'warning'
                className: 'notyf__toast--warning'
                backgroundColor: '#E3A008'
                icon: false
