dahromy_glide:
    source: '%kernel.project_dir%/public/uploads'
    cache: '%kernel.project_dir%/var/cache/glide'
    signature_key: '%env(GLIDE_SIGNATURE_KEY)%'
    # Add other default configuration options as needed

