# Documentation: https://github.com/redirectionio/proxy-symfony
redirection_io:
    project_key: FIXME
    connections:
        my_agent: tcp://127.0.0.1:10301
        # another_agent: unix:///var/run/redirectionio.sock
