services:
    _defaults:
        autowire: true

    OskarStark\Doctrine\EventSubscriber\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
