parameters:
  vatri_google_drive.credentials_file: '%kernel.project_dir%/%env(VATRI_GOOGLE_DRIVE_CREDENTIALS_FILE)%'
  vatri_google_drive.redirect_after_login_url: '%env(VATRI_GOOGLE_DRIVE_REDIRECT_AFTER_AUTH)%'
#  vatri_google_drive.session_access_token_key: vatri_google_drive.access_token
  vatri_google_drive.cookie_access_token_key: vatri_google_drive_access_token
  vatri_google_drive.session.key.redirect_path_after_auth: vatri_google_drive.session_redirect_path_after_auth

services:

  vatri_google_drive.cookie_token_storage:
    class: Vatri\GoogleDriveBundle\Service\CookieTokenStorage
    arguments:
      - '@request_stack'
      - '%vatri_google_drive.cookie_access_token_key%'

  vatri_google_drive.api_service:
    class: Vatri\GoogleDriveBundle\Service\DriveApiService
    arguments: [ '@session', '@parameter_bag', '@vatri_google_drive.cookie_token_storage' ]

  # Alias:
  Vatri\GoogleDriveBundle\Service\DriveApiService: '@vatri_google_drive.api_service'

  Vatri\GoogleDriveBundle\Controller\VatriGoogleDriveAuthController:
    public: true
    arguments:
      $parameterBag: '@parameter_bag'
      $session: '@session'
      $driveApiService: '@vatri_google_drive.api_service'
