KunstmaanCookieBundle:
    resource: "@KunstmaanCookieBundle/Resources/config/routing.yml"
    # If your site is not multilanguage, remove the "{_locale}/" part of prefix and requirements
    prefix:   /{_locale}/
    requirements:
        _locale: "%kunstmaan_admin.required_locales%"
