parameters:
    sulu_admin.name: SULU
    sulu_admin.email: johannes@sulu.io

sulu_admin:
    name: "%sulu_admin.name%"
    email: "%sulu_admin.email%"

sulu_security:
    checker:
        enabled: true
