services:
    _defaults:
        autowire: true

    Datana\Iusta\Api\IustaClient:
        arguments:
            - '%env(IUSTA_API_BASE_URI)%'
            - '%env(IUSTA_API_TOKEN)%'

    Datana\Iusta\Api\CaseApi: null
    Datana\Iusta\Api\CaseApiInterface: '@Datana\Iusta\Api\CaseApi'

    Datana\Iusta\Api\DatasetApi: null
    Datana\Iusta\Api\DatasetApiInterface: '@Datana\Iusta\Api\DatasetApi'

    Datana\Iusta\Api\ImportApi: null
    Datana\Iusta\Api\ImportApiInterface: '@Datana\Iusta\Api\ImportApi'
