_sfs_cms_pages_:
    resource: "@SfsCmsBundle/config/routing/admin_pages.yaml"
    prefix: "/admin/pages"

# CONFIGURE YOUR CUSTOM CONTENT TYPES ADMIN ROUTES
# _sfs_cms_custom_:
#     resource: "@SfsCmsBundle/config/routing/admin_content_type.yaml",
#     prefix: "/admin/custom"
#     defaults:
#     _content_type: custom
#     name_prefix: sfs_cms_admin_content_custom_

_sfs_cms_routes_:
    resource: "@SfsCmsBundle/config/routing/admin_routes.yaml"
    prefix: "/admin/routes"

_sfs_cms_menus_:
    resource: "@SfsCmsBundle/config/routing/admin_menus.yaml"
    prefix: "/admin/menus"

_sfs_cms_blocks_:
    resource: "@SfsCmsBundle/config/routing/admin_blocks.yaml"
    prefix: "/admin/blocks"

_sfs_cms_sites_:
    resource: "@SfsCmsBundle/config/routing/admin_sites.yaml"
    prefix: "/admin/sites"

_sfs_media_admin_types_:
    resource: "@SfsMediaBundle/config/routing/admin_media.yaml"
    prefix: "/admin/media"
