# Read the documentation: https://github.com/SebTM/inwx-api-bundle
inwx_api:
    debug: '%kernel.debug%'
    environment: development
    json: true
    language: en
    username: '%env(resolve:INWX_USERNAME)%'
    password: '%env(resolve:INWX_PASSWORD)%'
