league_oauth2_server:
    authorization_server:
        private_key: /var/oauth/private.key                     # Change this
        private_key_passphrase: null                            # Passphrase of the private key, if any
        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'   # (Optional) Change this
    resource_server:
        public_key: /var/oauth/public.key                       # Change this
    scopes:
        available: [EMAIL]                                    # Change this
        default: [EMAIL]                                      # Change this
    persistence:
        doctrine: null
