svc_contactform:
    # Email adress for contact mails
    contact_mail:         dev@sv-systems.com

    # Which route should by called after amil sent
    route_after_send:     index

    # Enable captcha for contact form?
    enable_captcha:       false

    # Enable sending a copy of the contact request to me too?
    enable_copy_to_me:    true
