nfl_fastr_symfony:
    timezone: Europe/Berlin
    sources:
        playByPlay:
            baseUrl: https://github.com/guga31bb/nflfastR-data
            path: tree/master/data
        roster:
            baseUrl: https://github.com/mrcaseb/nflfastR-roster
            path: tree/master/data/seasons
