commercetools:
    api:
        default_client: 'default'
        clients:
            default:
                client_id: '%env(CTP_CLIENT_ID)%'
                client_secret: '%env(CTP_CLIENT_SECRET)%'
                project: '%env(CTP_PROJECT_KEY)%'
                scope: '%env(CTP_SCOPE)%'
                oauth_url: '%env(CTP_AUTH_URL)%'
                api_url: '%env(CTP_API_URL)%'
    defaults:
        country: DE
        context:
            locale: en
            graceful: true
    project_settings:
        countries:
            - DE
        currencies:
            - EUR
        languages:
            - en
        messages: false
