# Read the documentation: https://github.com/kunicmarko20/jms-messenger-adapter#documentation

framework:
    messenger:
        enabled: true
        serializer:
            id: messenger.transport.jms_serializer
