## This is a sample easy admin configuration
## Copy Page Section to your own easy admin configuration
#
imports:
    - { resource: "@OperaAdminBundle/Resources/config/easy_admin.yaml" }

# easy_admin:
#     design:
#         menu:
#             - { label: 'Layout', children: ['Page'] }
#             - { label: 'Content', children: ['Article', { label: 'Medias', route: 'opera_admin_media_list' }] }

#     entities:
#         Article:
#             class: App\Entity\Article
