endroid_prediction_io:
    event_server:
        url: http://prediction_io:7070
    apps:
        endroid:
            key: '%env(PREDICTION_IO_ACCESS_KEY)%'
            engines:
                recommendation:
                    url: https://prediction_io:8000
