        # extension order a activer
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\OrderExtension:
        arguments: ['%api_platform.collection.order%', '@api_platform.metadata.resource.metadata_factory']
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 100 }

    # extension paginator
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\PaginationExtension:
        arguments:
            - '@doctrine_mongodb'
            - '@request_stack'
            - '@api_platform.metadata.resource.metadata_factory'
            - '%api_platform.collection.pagination.enabled%'
            - '%api_platform.collection.pagination.client_enabled%'
            - '%api_platform.collection.pagination.client_items_per_page%'
            - '%api_platform.collection.pagination.items_per_page%'
            - '%api_platform.collection.pagination.page_parameter_name%'
            - '%api_platform.collection.pagination.enabled_parameter_name%'
            - '%api_platform.collection.pagination.items_per_page_parameter_name%'
            - '%api_platform.collection.pagination.maximum_items_per_page%'
            - '%api_platform.collection.pagination.partial%'
            - '%api_platform.collection.pagination.client_partial%'
            - '%api_platform.collection.pagination.partial_parameter_name%'
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 8 }

    # Extension EagerLoading
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\EagerLoadingExtension:
        arguments:
            - '@api_platform.metadata.property.name_collection_factory'
            - '@api_platform.metadata.property.metadata_factory'
            - '@api_platform.metadata.resource.metadata_factory'
            - '%api_platform.eager_loading.max_joins%'
            - '%api_platform.eager_loading.force_eager%'
            - null
            - null
            - '%api_platform.eager_loading.fetch_partial%'
            - '@serializer.mapping.class_metadata_factory'
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.item, event: kernel.view, method: onKernelView, priority: 64 }
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 64 }

    # extension filter a activer
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\FilterExtension:
        arguments: ['@api_platform.metadata.resource.metadata_factory', '@api_platform.filter_locator']
        tags:
            - { name: api_platform.doctrine_mongodb.odm.query_extension.collection, event: kernel.view, method: onKernelView, priority: 100 } # rend une réponse donc moins prioritaire


    # Ajout du filtre datefilter
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\DateFilter:
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.datefilter' }

    # Ajout du filtre ExistFilter
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\ExistFilter:
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.existfilter' }

    # Ajout du filtre NumericFilter
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\NumericFilter:
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.numericfilter' }

    # Ajout du filtre OrderFilter
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\OrderFilter:
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.orderfilter' }

    # Ajout du filtre OrderFilter
    Sol\ApiPlatform\MongoBridge\Bridge\Doctrine\Odm\Extension\Filter\RangeFilter:
        arguments: ['@doctrine_mongodb', null, '@logger']
        tags:
            - { name: 'api_platform.filter', id: 'mongo.rangefilter' 
