data_migrations:
    dir_name: '%kernel.project_dir%/src/DataMigrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DataMigrations
    name: My app migrations
