# Read the documentation: https://github.com/breithbarbot/cropper/blob/master/Resources/doc/index.md
breithbarbot_cropper:
    mappings:
#        user_avatar:
#            routes:
#                # Your personalized route which will take care of the save of the image
#                path_add:    'app_cropper_avatar_add'
#
#            # Definition of cropped image properties (width, height and ratio)
#            width:  400
#            height: 400
#            ratio:  1
