cache_tool:
    # Config mode: (cli|fastcgi)
    adapter: '%env(resolve:CACHETOOL_ADAPTER)%'
    # Config fastcgi url
    fastcgi: '%env(resolve:CACHETOOL_FASTCGI)%'

    # Disable APC commands
    apc: '%env(resolve:CACHETOOL_APC)%'
    # Disable APCu commands
    apcu: '%env(resolve:CACHETOOL_APCU)%'
    # Disable Opcache commands
    opcache: '%env(resolve:CACHETOOL_OPCACHE)%'
