mgd_stackdriver:
    credentials_json_file: "%kernel.project_dir%/config/keys/google_service_account.json"
    level: info

#    log_name: ~ # It takes service id from $_ENV vars

#    error_reporting:
#        enabled: true
#        ignore_400: true
#