# Enable and configure the scripts you'd like
silverback_common_js:
    google_analytics:
        # in each script you can also define the enabled key
        # and default blocks so you don't have to do this in your twig templates
        enabled: false
#        default_blocks:
#            page_view: ~
#            "ec/init":
#                currency: USD
    gtm: false
    twitter: false
    facebook_sdk: false
