shopware_app:
    name: '%env(SHOPWARE_APP_NAME)%'
    secret: '%env(SHOPWARE_APP_SECRET)%'
    # You should use doctrine or dynamodb as storage
    storage: 'in-memory'
    doctrine:
        shop_class: App\Entity\Shop
