spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder:    ~
                timeline:         'App\Entity\SonataTimeline'
                action:           'App\Entity\SonataTimelineAction'
                component:        'App\Entity\SonataTimelineComponent'
                action_component: 'App\Entity\SonataTimelineActionComponent'

    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm


sonata_timeline:
    manager_type: orm

    class:
        timeline:         'App\Entity\SonataTimeline'
        action:           'App\Entity\SonataTimelineAction'
        actionComponent:  'App\Entity\SonataTimelineActionComponent'
        component:        'App\Entity\SonataTimelineComponent'
