# Contao configuration
contao:
    web_dir:                  "%kernel.project_dir%/web"
    prepend_locale:           false
    encryption_key:           "%kernel.secret%"
    url_suffix:               .html
    upload_path:              files
    csrf_token_name:          contao_csrf_token
    pretty_error_screens:     true
    error_level:              8183 # E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED
    image:
        bypass_cache:         false
        target_dir:           "%kernel.project_dir%/assets/images"
        valid_extensions:     ['jpg', 'jpeg', 'gif', 'png', 'tif', 'tiff', 'bmp', 'svg', 'svgz']
        imagine_service:      ~
        imagine_options:
            jpeg_quality:     80
            interlace:        plane
        reject_large_uploads: false
    security:
        two_factor:
            enforce_backend:  false