services:
    phpmob.twig_modify_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@phpmob.twig_modify_cache_pool'

framework:
    cache:
        pools:
            phpmob.twig_modify_cache_pool:
                adapter: cache.app

phpmob_twig_modify:
    cache: phpmob.twig_modify_cache_provider
