silverback_api_component:
  website_name: New Website
  user:
    class_name: App\Entity\User
    email_verification:
      default: false
      verify_on_register: true
      deny_unverified_login: true
    change_email_address:
      default_verify_path: /verify-new-email/{{ username }}/{{ token }}
    password_reset:
      default_reset_path: /reset-password/{{ username }}/{{ token }}
  security:
    tokens:
      - '%env(API_SECRET_TOKEN)%'
  publishable:
    permission: "is_granted('ROLE_ADMIN')"
